name: Verify SSH Connection

on:
  push:
    branches: [ main ]

jobs:
  test-ssh-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Verifying SSH Connection
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}       # Variable para el host
          username: ${{ secrets.SERVER_USERNAME }}  # Variable para el usuario
          password: ${{ secrets.SERVER_PASSWORD }}  # Variable para la contraseÃ±a
          port: ${{ secrets.SERVER_PORT }}       # Variable para el puerto
          script: |
            echo "Connection to ${{ secrets.SERVER_HOST }} was successful!"
            cd "${{ secrets.PATH }}"
            git pull origin main
            git fetch
            echo '${{ secrets.ENV_FILE }}' > .env
            composer i
            composer dump-autoload
            php artisan migrate:fresh --seed
            php artisan optimize:clear

